parameters:
  module.recordview.attachment_limits:
    compact:
      XSmall: 1
      Small: 1
      Medium: 1
      Large: 2
      XLarge: 2
    default:
      XSmall: 1
      Small: 1
      Medium: 1
      Large: 2
      XLarge: 2
