App\MediaObjects\Entity\PublicImageMediaObject:
  file:
    mapping: public_image_media_object # required
    filename_property: filePath  # required
    size: size
    mime_type: mimeType
    original_name: originalName
    dimensions: dimensions
