App\MediaObjects\Entity\PrivateImageMediaObject:
  file:
    mapping: private_image_media_object # required
    filename_property: filePath  # required
    size: size
    mime_type: mimeType
    original_name: originalName
    dimensions: dimensions
